### ISSUE TITLE
[FE]01 - 개발환경세팅

### ISSUE THREAD

**Issue by joseph-wee** [JiguemStart/DailyGram#1]
## Description

- 개발시작전 필요한 라이브러리 설치 및 설정 세팅하기

## Tasks

- [ ] 필요한 기술 스텍 및 라이브러리 설치
- [ ] 작업할 파일 생성
- [ ] 필요한 이미지, 로고 등 추가
- [ ] CSS 초기화 작업

**Comment by intacka** [comment]
상세하게 써주세요
