### ISSUE TITLE
[FE]07 - 회원가입 페이지(API관련 제외)

### ISSUE THREAD

**Issue by joseph-wee** [JiguemStart/DailyGram#10]
## Description
- 회원가입 페이지 API관련 기능 제외하고 나머지 구현

## Tasks
- [x] 마크업, CSS 작업
- [x] 이메일, 이메일 재확인 체크 - 같지 않으면 빨간색 같으면 파란색 활성화
- [x] 비밀번호, 비밀번호 재확인 체크 - 같지 않으면 빨간색 같으면 파란색 활성화
