### ISSUE TITLE
[FE]08 - 로그인 페이지(API관련 제외)

### ISSUE THREAD

**Issue by joseph-wee** [JiguemStart/DailyGram#11]
## Description
- 로그인 페이지 API관련 기능 제외하고 나머지 구현하기

## Tasks
- [x] 마크업, CSS작업
- [x] 이메일 입력칸 place holder
- [x] 비밀번호 입력칸 place holder
- [x] 로그인 버튼 - 클릭 시 메인페이지로
- [x] 비밀번호 찾기 버튼 - 클릭 시 비밀번호 찾기 페이지로 이동
