### ISSUE TITLE
[FE]09 - 일기작성 페이지(API관련 제외)

### ISSUE THREAD

**Issue by joseph-wee** [JiguemStart/DailyGram#12]
## Description
- 일기작성 페이지 API관련 기능 제외하고 나머지 구현

## Tasks
- [x] 마크업, CSS작업
- [x] 날짜 입력칸 - default 값 오늘
- [x] 날씨, 기분, 제목, 내용 입력칸 - 클릭 시 활성화
- [x] 일기저장 버튼 - 빈칸 없으면 활성화, 클릭 시 일기 목록 페이지로 이동
