### ISSUE TITLE
[FE]10 -모바일 사이드바(API관련 제외)

### ISSUE THREAD

**Issue by joseph-wee** [JiguemStart/DailyGram#18]
## Description

- 화면이 모바일상태일 때의 사이드바 구현

## Tasks

- [x] 헤더바의 메뉴 버튼 클릭시 모바일 사이드바 노출
- [x] 각 메뉴 버튼 디자인 구현
- [x] 각 메뉴 버튼 클릭시 해당 페이지로 이동
