### ISSUE TITLE
[FE]02 - 메인 페이지(API관련 제외)

### ISSUE THREAD

**Issue by joseph-wee** [JiguemStart/DailyGram#5]
## Description
- 메인페이지 API관련 기능 제외하고 나머지 구현

## Tasks
- [x] 마크업, CSS 작업
- [x] 소개
- [x] 로그인 유무에 따라 일기작성 버튼 혹은 로그인버튼, 회원가입 버튼 노출
- [x] 로그인버튼 - 클릭 시 로그인 페이지로 이동
- [x] 회원가입버튼 - 클릭 시 회원가입 페이지로 이동
