### ISSUE TITLE
[FE]03 - 사이드 바(API관련 제외)

### ISSUE THREAD

**Issue by joseph-wee** [JiguemStart/DailyGram#6]
## Description
- 사이드 바 API관련 기능 제외하고 나머지 구현

## Tasks
- [x] 마크업, CSS 작업
- [x] 메뉴 버튼 클릭 시 해당 페이지로 이동
- [x] 반응형 작업 - 가로 너비에 따라 위치변경
