### ISSUE TITLE
[FE]04 - 헤더 바(API관련 제외)

### ISSUE THREAD

**Issue by joseph-wee** [JiguemStart/DailyGram#7]
## Description
- 헤더 바 API관련 기능 제외하고 나머지 구현

## Tasks
- [x] 마크업, CSS 작업
- [x] 각 버튼 클릭 시 해당 페이지로 이동
- [x] 반응형 작업 - 가로 너비에 따라 버튼 위치 변경
